<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;

class AdministratorOperaterDesktopBackofficeMenuTest extends DuskTestCase
{
    private $home_page = '/backoffice-tombola/public/en/home_page';
    private $backoffice_username = "";
    private $backoffice_password = "";

    public function setUp()
    {
        $this->backoffice_username = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_USERNAME");
        $this->backoffice_password = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_PASSWORD");
        $this->home_page = getenv('TEST_HOME_PAGE_URL_FOR_BROWSER_TESTING');
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Throwable
     */
    public function testLoginBackoffice()
    {
        $username = $this->backoffice_username;
        $password = $this->backoffice_password;

        $this->browse(function (Browser $browser) use($username, $password){
            $browser->visit('')
                ->type('username', $username)
                ->type('password', $password)
                ->press('login')
                ->assertPathIs($this->home_page)
                ->assertSee(__("authenticated.Home"))
            ;
            $browser->click("#toggleSideBar");
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewMyAccountOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                //->visit($this->test_page_url)
                ->assertSee(__("authenticated.My Account"))
                ->clickLink(__("authenticated.My Account"))
                ->pause(1000)
                ->assertSee(__("authenticated.My Personal Data"))
                ->assertSee(__("authenticated.Change Password"))
                ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewAdministrationOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->assertSee(__("authenticated.Administration"))
                ->clickLink(__("authenticated.Administration"))
                ->pause(1000)
                ->assertDontSee(__("authenticated.Translation"))
                ->assertDontSee(__("authenticated.Login Form"))
                ->assertSee(__("authenticated.Parameter Setup"))
                ->clickLink(__("authenticated.Parameter Setup"))
                ->pause(1000)
                ->assertDontSee(__("authenticated.Add New Parameter"))
                ->assertSee(__("authenticated.Entity List - Parameter Setup"))
                ->assertDontSee(__("authenticated.Version Setup"))
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testLogoutBackoffice()
    {
        $this->browse(function (Browser $browser) {
            //$browser->pause(1000);
            $browser->clickLink(__("authenticated.Logout"))
            ;
        });
    }
}
