<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use App\Helpers\StringHelper;

class NewStructureEntityTest extends DuskTestCase
{
    private $home_page = '/backoffice-tombola/public/en/home_page';
    private $backoffice_username = '';
    private $backoffice_password = '';

    public function setUp()
    {
        $this->backoffice_username = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_USERNAME");
        $this->backoffice_password = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_PASSWORD");
        $this->home_page = getenv('TEST_HOME_PAGE_URL_FOR_BROWSER_TESTING');
        return parent::setUp(); // TODO: Change the autogenerated stub
    }
    /**
     * @throws \Throwable
     */
    public function testBasicExample()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('')
                    ->assertSee('Partner Network');
        });
    }

    /**
     * @throws \Throwable
     */
    public function testLoginBackoffice()
    {

        $username = $this->backoffice_username;
        $password = $this->backoffice_password;

        //$username = getenv('BACKOFFICE_USERNAME');
        //$password = getenv('BACKOFFICE_PASSWORD');

        $this->browse(function (Browser $browser) use($username, $password){
            $browser->visit('')
                    ->type('username', $username)
                    ->type('password', $password)
                    ->press('login')
                    ->assertPathIs($this->home_page);
            ;
            $browser->click("#toggleSideBar");
        });
    }

    /**
     * @throws \Throwable
     */
    public function testVisitUserNewUserPage()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit("newStructureEntity2")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testCreateNewOperater()
    {
        $user_random_name = StringHelper::player_random_name('testOperater_');

        $this->browse(function (Browser $browser) use ($user_random_name){
            $browser->visit("newStructureEntity2")
                ->select('subject_type', config('constants.OPERATER_TYPE_ID'))
                ->pause(3000)
                ->select('parent_affiliate')
                ->pause(3000)
                ->select('draw_model')
                ->select('currency', 'EUR')
                ->type('username', $user_random_name)
                ->type('password', $user_random_name)
                ->type('confirm_password', $user_random_name)
                ->type('first_name', $user_random_name)
                ->type('last_name', $user_random_name)
                ->type('mobile_phone', "011123456798")
                ->type('email', $user_random_name . '@' . 'sharklasers.com')
                ->type('address', $user_random_name)
                ->type('commercial_address', $user_random_name)
                ->type('post_code', '11000')
                ->type('city', 'Belgrade')
                ->select('country')
                ->select('language')
                ->pressAndWaitFor('save', 5)
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testCreateNewLocation()
    {
        $user_random_name = StringHelper::player_random_name('testLocation_');

        $this->browse(function (Browser $browser) use ($user_random_name){
            $browser->visit("newStructureEntity2")
                ->select('subject_type', config('constants.LOCATION_TYPE_ID'))
                ->pause(3000)
                ->select('parent_affiliate')
                ->pause(3000)
                ->select('draw_model')
                ->select('currency', 'EUR')
                ->type('username', $user_random_name)
                ->type('password', $user_random_name)
                ->type('confirm_password', $user_random_name)
                ->type('first_name', $user_random_name)
                ->type('last_name', $user_random_name)
                ->type('mobile_phone', "011123456798")
                ->type('email', $user_random_name . '@' . 'sharklasers.com')
                ->type('address', $user_random_name)
                ->type('commercial_address', $user_random_name)
                ->type('post_code', '11000')
                ->type('city', 'Belgrade')
                ->select('country')
                ->select('language')
                ->pressAndWaitFor('save', 5)
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testCreateNewCashierTerminal()
    {
        $user_random_name = StringHelper::player_random_name('testCashierTerminal_');

        $this->browse(function (Browser $browser) use ($user_random_name){
            $browser->visit("newStructureEntity2")
                ->select('subject_type', config('constants.TERMINAL_CASHIER_TYPE_ID'))
                ->pause(3000)
                ->select('parent_affiliate')
                ->pause(3000)
                ->select('currency', 'EUR')
                ->type('username', $user_random_name)
                ->type('password', $user_random_name)
                ->type('confirm_password', $user_random_name)
                ->type('first_name', $user_random_name)
                ->type('last_name', $user_random_name)
                ->type('mobile_phone', "011123456798")
                ->type('email', $user_random_name . '@' . 'sharklasers.com')
                ->type('address', $user_random_name)
                ->type('commercial_address', $user_random_name)
                ->type('post_code', '11000')
                ->type('city', 'Belgrade')
                ->select('country')
                ->select('language')
                ->pressAndWaitFor('save', 5)
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testCreateNewTerminalSales()
    {
        $user_random_name = StringHelper::player_random_name('testTerminalSales_');

        $this->browse(function (Browser $browser) use ($user_random_name){
            $browser->visit("newStructureEntity2")
                ->select('subject_type', config('constants.TERMINAL_SALES_TYPE_ID'))
                ->pause(3000)
                ->select('parent_affiliate')
                ->pause(3000)
                ->select('currency', 'EUR')
                ->type('username', $user_random_name)
                ->type('password', $user_random_name)
                ->type('confirm_password', $user_random_name)
                ->type('first_name', $user_random_name)
                ->type('last_name', $user_random_name)
                ->type('mobile_phone', "011123456798")
                ->type('email', $user_random_name . '@' . 'sharklasers.com')
                ->type('address', $user_random_name)
                ->type('commercial_address', $user_random_name)
                ->type('post_code', '11000')
                ->type('city', 'Belgrade')
                ->select('country')
                ->select('language')
                ->pressAndWaitFor('save', 5)
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testLogoutBackoffice()
    {
        $this->browse(function (Browser $browser) {
            //$browser->pause(1000);
            $browser->clickLink("Logout")
            ;
        });
    }
}
