<?php

namespace Tests\Browser;

use Tests\DuskTestCase;
use Laravel\Dusk\Browser;

class AdministratorOperaterDesktopPermissionAccessTest extends DuskTestCase
{
    private $home_page = '/backoffice-tombola/public/en/home_page';
    private $backoffice_username = "";
    private $backoffice_password = "";
    private $test_page_url = '/home_page';

    public function setUp()
    {
        $this->backoffice_username = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_USERNAME");
        $this->backoffice_password = getenv("ADMINISTRATOR_OPERATER_BACKOFFICE_PASSWORD");
        $this->home_page = getenv('TEST_HOME_PAGE_URL_FOR_BROWSER_TESTING');
        return parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Throwable
     */
    public function testLoginBackoffice()
    {
        $username = $this->backoffice_username;
        $password = $this->backoffice_password;

        $this->browse(function (Browser $browser) use($username, $password){
            $browser->visit('')
                ->type('username', $username)
                ->type('password', $password)
                ->press('login')
                ->assertPathIs($this->home_page)
                ->assertSee('Home')
            ;
            $browser->click("#toggleSideBar");
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewMyAccountOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/my-account/my-personal-data")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/my-account/my-personal-data")
                ->visit("/my-account/change-password")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/my-account/change-password")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewAdministrationOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/administration/search-users")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/search-users")

                ->visit("/administration/language-setup/list-language-file-for-login")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/language-setup/list-language-file-for-login")

                ->visit("/administration/language-setup/list-language-file-for-authenticated")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/language-setup/list-language-file-for-authenticated")

                ->visit("/administration/version-setup/version-setup")
                ->assertPathIsNot(getenv("TEST_APPLICATION_NAME") . "/administration/version-setup/version-setup")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/messages/index")

                ->visit("/administration/parameter-setup/add-new-parameter")
                ->assertPathIsNot(getenv("TEST_APPLICATION_NAME") . "/administration/parameter-setup/add-new-parameter")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/messages/index")

                ->visit("/administration/entity-parameter-setup/list-entities")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/entity-parameter-setup/list-entities")

                ->visit("/administration/list-draw-models")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/list-draw-models")

                ->visit("/administration/create-draw-model")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administration/create-draw-model")

                ->visit("/jackPotSetup")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/jackPotSetup")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewStructureEntityOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/newStructureEntity2")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/newStructureEntity2")

                ->visit("/structure-entity/search-entity")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/structure-entity/search-entity")

                ->visit("/structure-entity/list-users-tree")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/structure-entity/list-users-tree")
                ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewUsersOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/newUser2")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/newUser2")

                ->visit("/user/search-users")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/user/search-users")

                ->visit("/administrator/list-administrators")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/administrator/list-administrators")

                ->visit("/terminal/list-terminals")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/terminal/list-terminals")

                ->visit("/player/list-players")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/player/list-players")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewCreditTransfersOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/transfer-credit/deposit-list")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/transfer-credit/deposit-list")

                ->visit("/transfer-credit/withdraw-list")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/transfer-credit/withdraw-list")

                ->visit("/transfer-credit/deposit-user-structure-view")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/transfer-credit/deposit-user-structure-view")

                ->visit("/transfer-credit/withdraw-user-structure-view")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/transfer-credit/withdraw-user-structure-view")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewTicketsOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/ticket/search-tickets")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/ticket/search-tickets")

                ->visit("/ticket/list-temporary-tickets")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/ticket/list-temporary-tickets")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testViewReportsOnMainMenu(){
        $this->browse(function (Browser $browser){
            $browser
                ->visit("/report/ticket-list")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/ticket-list")

                ->visit("/report/draw-list")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/draw-list")

                ->visit("/allTransactionsReport")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/allTransactionsReport")

                ->visit("/report/financial-report")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/financial-report")

                ->visit("/report/collector-transaction-report")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/collector-transaction-report")

                ->visit("/report/transaction-report")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/transaction-report")

                ->visit("/report/player-liability-report")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/player-liability-report")

                ->visit("/dailyCashierReport")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/dailyCashierReport")

                ->visit("/report/list-login-history")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/report/list-login-history")

                ->visit("/machineKeysAndCodes")
                ->assertPathIs(getenv("TEST_APPLICATION_NAME") . "/machineKeysAndCodes")
            ;
        });
    }

    /**
     * @throws \Throwable
     */
    public function testLogoutBackoffice()
    {
        $this->browse(function (Browser $browser) {
            //$browser->pause(1000);
            $browser->clickLink("Logout")
            ;
        });
    }
}
